### ISSUE TITLE
When changing item category generated password gets lost

### ISSUE THREAD

**Issue by bondezbond** [1Password/terraform-provider-onepassword#13]
### Your environment

Terraform Provider Version: 1.0.0
Connect Server Version: 1.0.0

OS: macOs Big Sur 11.2.3

Terraform Version: 0.15.2

## What happened?
Created a test op item as `category: password` with only password recipe all other variables blank. It create the password item successfully and I see the password in vault. When changing the category to `login` terraform shows that it'll change the category type BUT it blanks out the password in the vault. Example code

```
resource "onepassword_item" "item" {
  vault = var.vault

  title    = var.name // test
  category = var.category // password -> login

  username = var.username // default ""
  database = var.database // default ""
  hostname = var.hostname // default ""
  port     = var.port // default ""

  password_recipe {
    length  = 40
    symbols = false
  }
}
```
![image](https://user-images.githubusercontent.com/4400773/116544542-4aabf200-a8bd-11eb-9765-f5c668229438.png)

## What did you expect to happen?
I expected it to change the category type successfully and the resource in vault would convert the item to login without it blanking out the password in vault.

If changing category types aren't possible I would expect the provider to error out.

## Steps to reproduce
1. Run apply with category as `password`
2. Run second apply with category as `login`

**Comment by jpcoenen** [comment]
Hi :wave: 

Thank you for your extensive bug report! You are very right that changing the category should not be possible in the way it is currently allowed. I opened a [PR](https://github.com/1Password/terraform-provider-onepassword/pull/16) to make sure that Terraform recreates the item when you change the category.
