### ISSUE TITLE
Support for Secure Note

### ISSUE THREAD

**Issue by MikeySoftNL** [1Password/terraform-provider-onepassword#149]
### Summary
Currently the onepassword provider can only manage items of types (login, password, database), where onepassword supports about 21 types.

This feature request is specifically for the Secure Note type, but it would be great if all type could be supported in the (near) future

We use the Secure Note all the time, but unfortunately this type cannot be created or updated using the 1Password/onepassword provider.

Currently we are leveraging the anasinnyk/onepassword provider for this, but this requires to use the onepassword cli 1.4.0 which is very old.

### Use cases
Larger secure texts
JSON objects
credential files
SSH Keys
etc.

**Comment by sdahlbac** [comment]
The fact that we are missing Secure Note AND Document is a blocker for us
