### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by elct9620** [1Password/terraform-provider-onepassword#24]
### Your environment

Terraform Provider Version: v1.0.2

Connect Server Version: v1.1.1

OS: macOS BigSur

Terraform Version: v0.15.3

## What happened?

When running `terraform apply` but got 401 Unauthorized error

## What did you expect to happen?

Run success and create a new password item

## Steps to reproduce

Run `terrform apply`

## Notes & Logs

The server logs
```
2021-05-15 08:25:13 | stdout | {"log_message":"(I) POST /v1/vaults/bmtferd2cmdmi6ejx5jelmu4xy/items completed (401: Unauthorized)","timestamp":"2021-05-15T08:25:13.828612223Z","level":3,"scope":{"request_id":"3b110817-a0a0-4708-873d-02a29d91583a"}}
-- | -- | --
2021-05-15 08:25:13 | stdout | {"log_message":"(E) Server: (failed to unverifiedTokenFromRequest), 401: Invalid bearer token","timestamp":"2021-05-15T08:25:13.828472374Z","level":1,"scope":{"request_id":"3b110817-a0a0-4708-873d-02a29d91583a"}}
2021-05-15 08:25:13 | stdout | {"log_message":"(W) Server: (could not parse JWT), failed to ParseSigned: illegal base64 data at input byte 84","timestamp":"2021-05-15T08:25:13.828399163Z","level":2,"scope":{"request_id":"3b110817-a0a0-4708-873d-02a29d91583a"}}


```

**Comment by jpcoenen** [comment]
Hi @elct9620 :wave:,

Thank you for your report! Looking at the error message, I think I know what happened here. Only the first 83 characters of the token (`OP_CONNECT_TOKEN`) got copied . 

I tried reproducing this on 1Password.com and is indeed indeed possible to only select only the first part of the token if you're not using the copy button. It is difficult to notice if this is happening. So I'll file an issue internally to fix this in the web interface.

To fix your problem right now, there are two options:
 - If you have saved the token to any of your vaults after creating it, you should be able to copy the full token and use that instead. 
 - If you did not save it, I suggest revoking the old token and generating a new one. I recommend using the copy button (see below) on the right side of the text area for now. This guarantees you're copying the full token.

![image](https://user-images.githubusercontent.com/1965218/118646326-5b76c600-b7e0-11eb-8d31-003aa6892aa3.png)


Let me know if that solves it for you.

**Comment by elct9620** [comment]
@jpcoenen 

My `terraform.tfvars` contains 641 characters token. I also try to append `\n` after the token and the terraform's error message shows the full token in my console. But I am not sure the reason cause it didn't send the full token.

**Comment by jpcoenen** [comment]
That does indeed correspond to the correct length of a token. What made me think that I was certain of what was wrong, was this part of the error message:

```
failed to ParseSigned: illegal base64 data at input byte 84
```
It suggests there is a problem with the token around character 84. Could check if anything unusual happens around character 84 of the token. With unusual I mean a character that is not a letter, a number, `-`, or `_`.

**Comment by elct9620** [comment]
My token didn't contain the unusual character, I also try to create another token but still have the same problem.

If I append the `\n` at the end of the token, the terraform error message shows the full token.
![截圖 2021-05-21 上午12 38 52](https://user-images.githubusercontent.com/887984/119016979-1c599800-b9cd-11eb-880e-08f322ba93d1.png)

**Comment by elct9620** [comment]
Each token I generated is unable to use terraform to send the API request. But these tokens can correctly call the API via `curl` because I use the same token to find my vault id.

**Comment by jpcoenen** [comment]
Okay, good to know it is Terraform-only. That helps a lot.

Let's dive a bit deeper to see what is going on. Could you maybe share the Terraform code and `terraform.tfvars` you are using? You can replace any sensitive values with a placeholder (e.g. `<token>`).

**Comment by elct9620** [comment]
My `terraform.tfvars`

```
cloudflare_api_token="<token>"
do_token="<token>"
onepassword_token="<token>"
onepassword_url="http://172.31.1.175:8080"
onepassword_vault="<vault_id>"
```

The terraform I am using for the test

```
variable "onepassword_url" {
  description = "1Password Connect Server URL"
}

variable "onepassword_token" {
  description = "1Password Connect Access Token"
}

provider "onepassword" {
  url = var.onepassword_url
  token = var.onepassword_token
}

variable "onepassword_vault" {
  description = "1Password Vault for Database"
}

resource "onepassword_item" "demo_password" {
  vault = var.onepassword_vault

  title    = "Demo Password Recipe"
  category = "password"

  password_recipe {
    length  = 40
    symbols = false
  }
}
```

**Comment by jpcoenen** [comment]
That code seems to be okay :smiley:  Unfortunately that also means I am having some troubles reproducing the issue locally. I am going to ask around to see if anyone else has some suggestions what is going on here.

One thing you could check in the meantime is if, by any chance, the _last_ character of the token is missing. That is another way to get this exact (`illegal base64 data at input byte 84`) error.

**Comment by jpcoenen** [comment]
We're getting somewhere now! 

Could it be that the token only has read access to the vault you're using? Version 1.1 of Connect returns a `401` in that case, including a message that this is the case. Unfortunately, our Go SDK (and therefore the Terraform Provider) does not present this message to you, yet. Getting this fixed,  [is in the works](https://github.com/1Password/connect-sdk-go/issues/17).

If this is not the solution, a way to get the message behind the error (while the SDK is not updated), is performing a POST through cURL:
```
curl -X POST -H "Authorization: Bearer $OP_TOKEN" http://172.31.1.175:8080/v1/vaults/bmtferd2cmdmi6ejx5jelmu4xy/items | jq
```

**Comment by elct9620** [comment]
When I use curl to send the POST request, it returns a 401 error. The config in my 1Password vault already gives full access to this token.

**Comment by jpcoenen** [comment]
> When I use curl to send the POST request, it returns a 401 error. The config in my 1Password vault already gives full access to this token.

Could you share the exact response? The included `message` field (or lack thereof) would be helpful in finding a solution.

For example, this is what I got from performing the request with a read-only token (it should show a different message in your case):

```
$ curl -X POST -H "Authorization: Bearer $OP_TOKEN" http://localhost:8080/v1/vaults/dj8290av5i7gextkqv45g7algw4/items | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    94  100    94    0     0     92      0  0:00:01  0:00:01 --:--:--    92
{
  "status": 401,
  "message": "Unauthorized Request, token does not have write access to the Vault"
}
```

**Comment by elct9620** [comment]
The message return from my connect api server

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    94  100    94    0     0   5529      0 --:--:-- --:--:-- --:--:--  5529
{
     "status" => 401,
    "message" => "Unauthorized Request, token does not have write access to the Vault"
}
```

**Comment by jpcoenen** [comment]
It looks like the token does not have write access to the vault. The Connect instance and Access Token must both have write access to the vault.

You can check this, by unfolding the details of the token on the Connect details page. The vault you're using should be listed as `Read, Write` for the access token:
![image](https://user-images.githubusercontent.com/1965218/119697735-cebbb000-be50-11eb-99ce-301c93ad40e5.png)

And it should also be listed as `Read, Write` for the Connect instance itself:
![image](https://user-images.githubusercontent.com/1965218/119697809-e2ffad00-be50-11eb-94f4-8bbfbf18f779.png)

For the Connect instance, you can click the gear to change the permissions. If the write permission is missing for the Access Token, you can best create a new token write read + write permissions. Make sure to enable both read and write after selecting the vault:
![image](https://user-images.githubusercontent.com/1965218/119698102-3114b080-be51-11eb-98fd-8bdf22c2dce5.png)

Let me know if that helps :blush:

**Comment by elct9620** [comment]
Oh, I notice my token is read-only. The new token is works correctly, thanks.

**Comment by jpcoenen** [comment]
Awesome! Glad you got it to work :+1:
