### ISSUE TITLE
Add datasources for vault and retrieving items from onepassword not stored using this provider

### ISSUE THREAD

**Issue by Hitesh-Agrawal** [1Password/terraform-provider-onepassword#25]
### Summary

Add datasources for vault and retrieving items from onepassword.

### Use cases
Currently we can retrieve items from onepassword which are stored/created using this provider only.

Allow to retrieve items which are not stored using this provider.

### Proposed solution

For e.g
data "onepassword_vault" "secret" {
    name = "Secret"
}

data "onepassword_item" "example" {
  category = "login"
  title    = "test"
  vault_id  = data.onepassword_vault.secret.id
  uuid  =   "There should be a way(datasource) to  retrieve the uuid of the items using title"
}

Now in your code to retrieve the password

output "example" {
  value = data.onepassword_item.example.password
}
### References & Prior Work

* 
*

**Comment by mcmarkj** [comment]
This is _EXACTLY_ what I just came here to raise an issue for. It's very fiddly having to put the vault UUID into Terraform as a variable, in theory I'd much prefer if the provider could find it for me.

**Comment by jpcoenen** [comment]
You are very right that a vault data source would be useful. I just opened a [PR](https://github.com/1Password/terraform-provider-onepassword/pull/28) to add this. Let me know if this solves your needs.

Thanks for your suggestion :raised_hands:

**Comment by mcmarkj** [comment]
Hey @jpcoenen I think there's a second part to this issue which your PR isn't going to resolve. The concept being that a UUID should be an optional field for onepassword_item data resources and that an item can be found via either UUID or Title.

**Comment by jpcoenen** [comment]
@mcmarkj Thank you for pointing that out. I have just merged a [PR](https://github.com/1Password/terraform-provider-onepassword/pull/30) that addresses this. It will be included in the next release.
