### ISSUE TITLE
Support darwin_arm64 / apple silicon

### ISSUE THREAD

**Issue by wonko** [1Password/terraform-provider-onepassword#35]
Goreleaser won't build the darwin_arm64 target as the go version is too old. 

See https://github.com/1Password/terraform-provider-onepassword/runs/2773180408?check_suite_focus=true#step:5:33

Submitted #34 .

**Comment by jpcoenen** [comment]
Thank you for bringing this to our attention. Easy to overlook if you're not using M1 :sweat_smile: 

The just-released `v1.1.1` contains a build for `darwin/arm64` :tada:
