### ISSUE TITLE
Cannot create (T)OTP fields

### ISSUE THREAD

**Issue by drdaeman** [1Password/terraform-provider-onepassword#54]
### Your environment

Terraform Provider Version: 1.1.3

Connect Server Version: 1.5.0

OS: any

Terraform Version: 1.0.7, but it shouldn't matter

## What happened?
Trying to create a field with type "TOTP" causes a validation error coming from the Connect server:

    Error: status 400: Validation: (validateVaultItem failed to Validate), Couldn't validate the item: "[ItemValidator] has found 1 errors, 0 warnings: \nErrors: {1. details.sections[1].fields[0] has unsupported field type: totp}"

According to the https://github.com/1Password/connect/pull/26 the correct value for `field.type` is "OTP" rather than "TOTP". Can you please fix the `fieldTypes` array accordingly?

https://github.com/1Password/terraform-provider-onepassword/blob/906b16d5c09d924acfe20301bc34499c0938cdcc/onepassword/resource_onepassword_item.go#L56

Thank you!

## Steps to reproduce

    resource "onepassword_item" "something" {
      ...
      section {
        ...
        field {
          label = "One-time password"
          type = "TOTP"
          value = ...
        }
      }
    }

**Comment by edif2008** [comment]
Good news. We have just released v1.1.4 which contains the fix to (T)OTP field type. 🎉 
Thank you for reporting this bug and also providing a PR with the fix! 😄
