### ISSUE TITLE
Edit notes field

### ISSUE THREAD

**Issue by dmwassman** [1Password/terraform-provider-onepassword#57]
### Summary
Add Notes to the optional schema for the onepassword_item resource
### Use cases

It would be helpful to be able to edit the Notes field in onepassword through the Terraform integration. This would provide an additional feature match to what can be done through OnePassword UI.

Our specific request resolve around adding anote to reference that the item was managed by Terraform. We can do this through a tag but the ideal solution would to expose the notes as a modified attribute.

**Comment by SBejga** [comment]
+1

We also need this feature. We find no other way to create an item in 1password with multi line strings. 
We can try to contribute a merge request for this, but we are new to terraform provider source code.
