### ISSUE TITLE
Section and field labels' case is not preserved.

### ISSUE THREAD

**Issue by midu-git** [1Password/terraform-provider-onepassword#59]
### Your environment

Terraform Provider Version: 1.1.4

Connect Server Version: 1.5.1

OS: macOS

Terraform Version:1.1.7

## What happened?
Define an item in 1password and assign a new section to it, "DATA" say. Inside this section, define a field, "appName" say. When calling this item using onepassword_item, the sections' label is "Data" and the label of the mentioned field is "appname".

## What did you expect to happen?
Sections' label should be "DATA" and fields' label should be "appName", i.e. the case should be preserved.
At least, both labels should be consistently modified => "data", "appname".

## Steps to reproduce
As described above.

## Notes & Logs
For the fields' name, the provider explicitly converts it to lower case
```go
dataField["label"] = strings.ToLower(f.Label)
```
The label of the section, however, is not modified in the provider. It is returned from a call to the sdk
```
github.com/1Password/connect-sdk-go
```
and there, just a 
```go
json.Unmarshal(body, result)
```
is called. Thus, the conversion needs to happen either in connect, or returned from 1password API, directly.

**Comment by midu-git** [comment]
Is anyone outside there noticing these bug reports?

**Comment by midu-git** [comment]
@edif2008 What does it mean that you labeled this bug? From outside it seems, that there is no further process here. Can you comment on this or even provide a timeline? Is there someone working on this issue?

**Comment by edif2008** [comment]
Hey @midu-git,

Apologies for the late reply. The `tracked` label means that we're monitoring this issue in our internal platforms. This is done to make sure that this issue doesn't fall through the cracks.

As for a timeline, I unfortunately cannot give you anything concrete. I will bump this issue with my team in the hopes that someone has the time to pick it up.

**Comment by midu-git** [comment]
Hey @edif2008. Thank you the clarification.
