### ISSUE TITLE
Duplicates are left behind when changing item name

### ISSUE THREAD

**Issue by csullivannet** [1Password/terraform-provider-onepassword#6]
Environment:
terraform: `0.14.8`
onepassword-provider: `0.2.0`
onepassword-connect: `0.5.3`

When changing an item name, the old item is not cleaned up.

e.g.

Change from:

```
resource "onepassword_item" "op_pg_ip" {
  vault = var.op_vault

  title    = "PostgreSQL - ${var.environment}"
  category = "password"
  password = random_string.psql.result
}
```

to

```
resource "onepassword_item" "op_pg_ip" {
  vault = var.op_vault

  title    = "PostgreSQL Password - ${var.environment}"
  category = "password"
  password = random_string.psql.result
}
```

And two items will now exist in the vault: `PostgreSQL Password - FOO` and `PostgreSQL - FOO`.
It is expected that only `PostgreSQL Password - FOO` exists after the change.

**Comment by edif2008** [comment]
Closing as this seems to work in latest version of the provider (v1.4.3 as of this writing). Feel free to reopen this if you're still encountering this.
