### ISSUE TITLE
Can't get secure_note value from Provider

### ISSUE THREAD

**Issue by levmichael3** [1Password/terraform-provider-onepassword#60]
## Your environment
---

Terraform Provider Version: 
Terraform v1.1.9
on darwin_amd64

Connect Server Version: ~> 1.0.1

OS: macOS

Terragrunt Version:
terragrunt version v0.36.8

Connect Server Version:

1.5.1

## What happened?
---
I'm trying to pull secure_note content with the provider and there is no field for it.

This is the terraform (masked) output:
```bash
  {
    "category" = "secure_note"
    "database" = null
    "hostname" = null
    "id" = "vaults/***/items/ov3e2sgbt2hufhxjej3vseosei"  ## <<< note the ID
    "password" = null
    "port" = null
    "section" = []
    "tags" = [
      "***",
    ]
    "title" = "***"
    "type" = null
    "url" = null
    "username" = null
    "uuid" = "***"
    "vault" = "***"
  },
```
While from the `curl` output I can get a more details info:

```bash
❯ curl \
-H "Accept: application/json" \
-H "Authorization: Bearer $OP_API_TOKEN" \
http://localhost:8050/v1/vaults/*****/items/ov3e2sgbt2hufhxjej3vseosei | jq -r
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2837    0  2837    0     0  15257      0 --:--:-- --:--:-- --:--:-- 17621
{
  "id": "ov3e2sgbt2hufhxjej3vseosei",
  "title": "****",
  "tags": [
    "***"
  ],
  "version": 3,
  "vault": {
    "id": "***"
  },
  "category": "SECURE_NOTE",
  "last_edited_by": "***",
  "created_at": "2022-04-27T08:48:32Z",
  "updated_at": "2022-05-01T11:39:08Z",
  "fields": [
    {
      "id": "notesPlain",
      "type": "STRING",
      "purpose": "NOTES",
      "label": "notesPlain",
      "value": "{<GOOD VALUE>"    ## <<<<<< Where is this in the output from the provider?  <<< *THIS IS WHAT I WANT*
    }
  ]
}
```

## What did you expect to happen?
---
The information from the secure_note.

I want `.fields[0].value`
## Steps to reproduce
Here is my Terrafrom code:
( I pass an array of secrets to retrieve)

```bash
variable "vault_name" {
  description = "The name of the Vault"

}
data "onepassword_vault" "this_vault" {
  # uuid  = var.vault_id
  name = var.vault_name
}
locals {
  secrets = toset(var.onepassword_secrets)
  env     = upper(var.env)
}

data "onepassword_item" "onepassword_secrets" {
  vault    = data.onepassword_vault.this_vault.uuid
  for_each = local.secrets
  title    = "${local.env} | ${each.key}"
}

```

## Notes & Logs
---
All other passwords/tokens received correctly.

Only the secure_note doesn't even have a felid for the info.

**Comment by azerbe** [comment]
This looks like a more general issue, as I face the exact same problem while using the ansible collection.

**Comment by barkanias** [comment]
Faced the same issue! hope there would be a solution for that asap.

**Comment by levmichael-cellwize** [comment]
@edif2008 Do you think that this issue will be addressed soon? I'm heading into wired work arounds 😢

**Comment by nissimuseri** [comment]
I faced in my env the same behavior, is anything new with this Issue?

**Comment by edif2008** [comment]
Hey there,

First of all, thank you for raising this. I deeply apologize for the late reply.

I can definitely see the use of this and it's sad that the lack of it leads to weird workarounds. I will bump this one with my team in the hopes someone has the time to address this properly.

Thank you for your patience.
