### ISSUE TITLE
Publish a new release of the provider

### ISSUE THREAD

**Issue by tagoro9** [1Password/terraform-provider-onepassword#71]
Hello, it seems the latest released version of the provider is [v1.1.4](https://github.com/1Password/terraform-provider-onepassword/releases/tag/v1.1.4), which was released back in January. 

Looking at this repository history, it seems that several changes have been merged to main (see [here](https://github.com/1Password/terraform-provider-onepassword/compare/v1.1.4...main)) that address a couple of bug fixes and other improvements such as https://github.com/1Password/terraform-provider-onepassword/pull/70 or https://github.com/1Password/terraform-provider-onepassword/pull/69 that would be nice to have.

If this is not the place to request for such thing, please let me know.

Thank you!

**Comment by FlorentATo** [comment]
Bump

**Comment by StevenCane** [comment]
https://github.com/1Password/terraform-provider-onepassword/releases/tag/v1.2.0

**Comment by volodymyrZotov** [comment]
Close it as there were several releases already with the latest `v1.3.1` at this moment.
