### ISSUE TITLE
Docs not showing up in the provider registry

### ISSUE THREAD

**Issue by orenmazor** [1Password/terraform-provider-onepassword#8]
![Screen Shot 2021-04-13 at 10 33 53 AM](https://user-images.githubusercontent.com/384279/114572362-6a001980-9c45-11eb-92fa-4daf408d7283.png)

heyas. looks like the provider registry isn't actually showing the docs.

**Comment by bondezbond** [comment]
very excited for this release looking forward to viewing the capabilities of this provider.

**Comment by bondezbond** [comment]
is there any update on the docs showing up on the registry?

**Comment by smartinov** [comment]
Would really be awesome if we had some sort of documentation there, like which resources do exist

**Comment by jpcoenen** [comment]
We've just opened a [PR](https://github.com/1Password/terraform-provider-onepassword/pull/20) for the docs. They will be included in the next release of the provider.
